server:
  port: ${SERVER_PORT:8081}

keycloak:
  auth-server-url: http://localhost:8080
  realm: fiap-keycloak

spring:
  jackson:
    default-property-inclusion: non_null
    locale: en_US
  security:
    oauth2:
      client:
        provider:
          fiap-keycloak:
            issuer-uri: http://localhost:8080/realms/fiap-keycloak
        registration:
          keycloak:
            provider: fiap-keycloak
            authorization-grant-type: authorization_code
            client-id: fiap-keycloak-confidential
            client-secret: secret
            scope: openid
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  application:
    name: ecommerce-thymeleaf

  thymeleaf:
    cache: false
    encoding: ISO-8859-1
    prefix: classpath:/templates/
    suffix: .html

  http:
    encoding:
      charset: ISO-8859-1

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update  # Ou 'create' para desenvolvimento
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:ORCL  # Verifique o nome da instância aqui
      username: RM553587
      password: 0406197
      driver-class-name: oracle.jdbc.OracleDriver

  messages:
    encoding: ISO-8859-1
    basename: messages

  h2:
    console:
      enabled: false  # Desabilitado pois você está usando Oracle
    show-sql: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
